# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Good Bad Show
email: matt@matt.cc
description: > # this means to ignore newlines until "baseurl:"
  Andy believes that a thing can be objectively good. Matt does not. So is this thing good or bad?
baseurl: "/goodbadshow" # the subpath of your site, e.g. /blog
author: "Matt McInerne and Andy Mangold"
showart: "http://icebox.5by5.tv/images/broadcasts/76/cover_quarter.jpg"
url: "http://mattmotel.github.io" # the base hostname & protocol for your site
twitter_username: goodbadshow

# Build settings
markdown: kramdown
permalink: "/:title"
